#!/bin/bash

PROGRAM='../replace'
FILES=('bear' 'cat' 'dog' 'elephant' 'hydra' 'otter')
CASES=('r RRR' 'cat bro' 'dog buldog' 'ele oops' 'dra XXX' 'tt yst') 

for i in ${!FILES[@]}; do
  case=${CASES[$i]}
  file=${FILES[$i]}
  from=$(cut -d ' ' -f 1 <(echo $case))
  to=$(cut -d ' ' -f 2 <(echo $case))

  echo "$file: $from -> $to"

  ${PROGRAM} ${FILES[$i]} $from $to 
  DIFF=`diff ${FILES[$i]}.replace ${FILES[$i]}.gauge`
  if [ ! -z "$DIFF" ]; then
    printf '\033[31m'"ERROR: $file differs"'\033[m''\n'
    exit 1
  fi
done

printf '\033[32m''OK''\033[m''\n'
